site_title: Stan Bouchet Photographie
watermark_name: Stan BOUCHET
hero_title: Bonjour et bienvenue sur ma galerie photos
about_text: "Je suis photographe amateur et je partage ici mes images, sans prétention, avec l’envie de vous faire découvrir mon univers.\r\n\r\nLe site est tout neuf et les albums arriveront au fur et à mesure.\r\n\r\nBonne visite !\r\n\r\nStan"
images_domain: http://stan-bouchet.eu
series_title: Séries
series_subtitle: J'espère que vous prendrez autant de plaisir à les voir que moi à les faire.
featured_photo_slug: concert-de-daniel-pastor-2026-04-07-002
