[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' https: data: blob:; script-src 'self' 'unsafe-eval' https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.netlify.com https://identity.netlify.com https://api.github.com; frame-ancestors 'none';"
